
# here is a demonstration of manual building of a seurat base imag to use to build child images. satijalab provide a ready to use Seurat image: satijalab/seurat:latest
# is possible to do :FROM satijalab/seurat:latest   So far the latest docker pubblished is v.5.0.0

# Start from a stable R image
FROM rocker/r-ver:4.5.1
#FROM seurat_v.5.3.1_base:latest
LABEL maintainer="Alexander Bontempo <bontix77@yahoo.it> - Github: bontix77"
LABEL description="Base Docker image for Seurat_v.5.3.1-based scRNA-seq analysis"

# Install system libraries that Seurat and its dependencies need
RUN apt-get update && apt-get install -y \
    ## crypto / web / compression
    libssl-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    liblzma-dev \
    libbz2-dev \
    zlib1g-dev \
    ## grafic and font
    libpng-dev \
    libjpeg-dev \
    libtiff5-dev \
    libfontconfig1-dev \
    libcairo2-dev \
    libxt-dev \
    libharfbuzz-dev \
    libfreetype6-dev \
    libfribidi-dev \
    ## numerica / math / mappe / unità
    libgsl-dev \
    libudunits2-dev \
    ## hdf5
    libhdf5-dev \
    hdf5-tools \
    ## build tools
    pkg-config \
    patch \
    cmake \
    ## (optional)
    libgit2-dev \
    libglpk40 \
    libgdal-dev \
    gdal-bin \
    libgeos-dev \
    libproj-dev \
    libudunits2-dev \
    gfortran \
    libgsl-dev \
    libfftw3-dev \
    && rm -rf /var/lib/apt/lists/*





RUN R -q -e "install.packages('qqconf')"
RUN R -q -e "install.packages('BiocManager')" \
 && R -q -e "BiocManager::install('multtest', ask = FALSE)" \
 && R -q -e "install.packages(c('mutoss', 'qqconf', 'metap'))"

RUN R -q -e "install.packages('sf')"
# Set CRAN mirror
RUN echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> /usr/local/lib/R/etc/Rprofile.site

# First update Matrix to a new enough version
RUN R -q -e "install.packages('Matrix',  dependencies = TRUE)"
RUN R -q -e "install.packages('SeuratObject', dependencies = TRUE)"

RUN R -q -e "install.packages('hdf5r')" 
RUN R -q -e "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev','https://bnprks.r-universe.dev')) \
;install.packages('BPCells')"
RUN R -q -e "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev','https://bnprks.r-universe.dev')) \
;install.packages('presto')"
RUN R -q -e "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev','https://bnprks.r-universe.dev')) \
;install.packages('glmGamPoi')"

RUN R -q -e "install.packages('Seurat', dependencies = TRUE)"

RUN R -e  "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/')) \
;install.packages('Rhtslib')"

RUN R -e  "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/')) \
;install.packages('Rsamtools')"

RUN R -e  "setRepositories(ind = 1:3, addURLs = c('https://satijalab.r-universe.dev', 'https://bnprks.r-universe.dev/')) \
;install.packages('Signac')"

RUN R -q -e "install.packages('remotes')"
RUN R -q -e "remotes::install_github('satijalab/seurat-data')"

RUN R -q -e "BiocManager::install(c('DirichletMultinomial','TFBSTools'),\
                                   ask = FALSE)"
RUN R -e "BiocManager::install('BSgenome.Hsapiens.UCSC.hg38')"
RUN R -q -e "remotes::install_github('satijalab/azimuth')"


RUN R -q -e "remotes::install_github('satijalab/seurat-wrappers')"